layout_spectrum: 0.49695698464399957
typography_spectrum: 0.9560289765196381
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.020451107214361726
  lightness: 0.23348261128972736
  saturation: 0.751119113760069
  rhythmicContrast: 0.9975000311261836
github: true
author:
  name: Alaena  VanderMost
  email: me@alaenavandermost.com
  url: tellmombo.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/24eac603-68f6-48d4-888c-42f1ee6e2d44.gif
name: tell-mombo
url: 'http://www.tellmombo.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e248d3d8-dee5-40a8-96c7-6ce86409e484.gif
title: 'Hey - What''s Up, Hello?'
content: []
description: Tell Mombo something good
purpose:
  - type: external
    url: 'https://play.google.com/store/apps/details?id=io.thegrid.app&hl=en'
    label: Get Started on Android
  - type: external
    url: 'http://app.thegrid.io'
    label: Get Started on Desktop
